.TH "ZAMAN" "1" "June 2023" "Zaman v1" "Zaman Manual"

.SH NAME
zaman \- A simple tool that prints (or saves) man pages in a PDF file for an easier reading.

.SH SYNOPSIS
.B zaman
[\fI\,OPTION\/\fR] [\fI\,MAN PAGE\/\fR]

.SH DESCRIPTION
A simple tool that prints (or saves) man pages in a PDF file via Zathura for an easier reading. It also allows you to navigate through all the man pages available on your system via Rofi or Dmenu.

.SH OPTIONS
.PP
You can directly specify the man page to print as a PDF in the command: zaman 'man page to open'
.br
e.g.: "zaman ls"
.PP

.TP 
.B \-m, \-\-menu
Print the list of all the available man pages in a dynamic menu (rofi or dmenu); allowing you to search for the one to print as a PDF (default operation).

.TP
.B \-o, \-\-output <man_page> <file>
Write the output to "file". Useful to save the PDF converted man page to a file of your choice:
.br
e.g.: "zaman -o ls ~/Documents/man/ls.pdf"

.TP
.B \-O, \-\-save <man_page>
Write the output to a PDF file named "man_<command>.pdf" inside your current directory. Useful to quickly save the PDF converted man page to a file:
.br
You can either select the man page to save as a PDF file via the rofi/dmenu list:
.br
e.g.: "zaman -O"
.br
Or you can directly specify the man page to save as a PDF file in the command:
.br
e.g.: "zaman -O ls"

.TP
.B \-v, \-\-version
Print the current version

.TP
.B \-h, \-\-help
Print the help

.SH EXIT STATUS
.TP
.B 0
if OK

.TP
.B 1
if problems (user tried to open a non-existing man page, user does not have any dynamic menu installed, user did not specify a man page or a file path when using the output option...)

.SH SEE ALSO
.BR zathura (1),
.BR rofi (1),
.BR dmenu (1),
.BR groff (1),
.BR echo (1),
.BR grep (1)

.SH BUGS
Please report bugs to the GitHub page https://github.com/Antiz96/zaman

.SH AUTHOR
Robin Candau <robincandau@protonmail.com>
